2021-04-20 09:24:03,633 INFO    MainThread:1139414 [internal.py:wandb_internal():88] W&B internal server running at pid: 1139414, started at: 2021-04-20 09:24:03.632779
2021-04-20 09:24:03,635 DEBUG   HandlerThread:1139414 [handler.py:handle_request():101] handle_request: check_version
2021-04-20 09:24:03,636 DEBUG   SenderThread:1139414 [sender.py:send():122] send: header
2021-04-20 09:24:03,636 DEBUG   SenderThread:1139414 [sender.py:send():122] send: request
2021-04-20 09:24:03,636 DEBUG   SenderThread:1139414 [sender.py:send_request():131] send_request: check_version
2021-04-20 09:24:03,636 INFO    WriterThread:1139414 [datastore.py:open_for_write():77] open: /home/ubuntu/evgeny/GEP-forecasts/EVERGI/wandb/run-20210420_092403-3bw8bbsh/run-3bw8bbsh.wandb
2021-04-20 09:24:03,739 DEBUG   SenderThread:1139414 [sender.py:send():122] send: run
2021-04-20 09:24:03,989 INFO    SenderThread:1139414 [sender.py:_start_run_threads():596] run started: 3bw8bbsh with start time 1618910643
2021-04-20 09:24:03,991 DEBUG   SenderThread:1139414 [sender.py:send():122] send: summary
2021-04-20 09:24:03,991 DEBUG   HandlerThread:1139414 [handler.py:handle_request():101] handle_request: run_start
2021-04-20 09:24:03,992 INFO    SenderThread:1139414 [sender.py:_save_file():730] saving file wandb-summary.json with policy end
2021-04-20 09:24:04,547 WARNING MainThread:1139414 [internal.py:wandb_internal():146] Internal process interrupt: 1
2021-04-20 09:24:05,256 DEBUG   HandlerThread:1139414 [meta.py:__init__():34] meta init
2021-04-20 09:24:05,257 DEBUG   HandlerThread:1139414 [meta.py:__init__():48] meta init done
2021-04-20 09:24:05,257 DEBUG   HandlerThread:1139414 [meta.py:probe():190] probe
2021-04-20 09:24:05,259 DEBUG   HandlerThread:1139414 [meta.py:_setup_git():180] setup git
2021-04-20 09:24:05,281 DEBUG   HandlerThread:1139414 [meta.py:_setup_git():187] setup git done
2021-04-20 09:24:05,281 DEBUG   HandlerThread:1139414 [meta.py:_save_code():69] save code
2021-04-20 09:24:05,288 DEBUG   HandlerThread:1139414 [meta.py:_save_code():90] save code done
2021-04-20 09:24:05,288 DEBUG   HandlerThread:1139414 [meta.py:_save_patches():107] save patches
2021-04-20 09:24:05,414 DEBUG   HandlerThread:1139414 [meta.py:_save_patches():149] save patches done
2021-04-20 09:24:05,414 DEBUG   HandlerThread:1139414 [meta.py:_save_pip():52] save pip
2021-04-20 09:24:05,415 DEBUG   HandlerThread:1139414 [meta.py:_save_pip():66] save pip done
2021-04-20 09:24:05,415 DEBUG   HandlerThread:1139414 [meta.py:probe():231] probe done
2021-04-20 09:24:05,419 DEBUG   SenderThread:1139414 [sender.py:send():122] send: files
2021-04-20 09:24:05,420 INFO    SenderThread:1139414 [sender.py:_save_file():730] saving file wandb-metadata.json with policy now
2021-04-20 09:24:05,420 INFO    SenderThread:1139414 [sender.py:_save_file():730] saving file code/EVERGI/forecaster_buildings.py with policy now
2021-04-20 09:24:05,539 INFO    SenderThread:1139414 [sender.py:_save_file():730] saving file diff.patch with policy now
2021-04-20 09:24:08,648 DEBUG   SenderThread:1139414 [sender.py:send():122] send: stats
2021-04-20 09:24:13,062 DEBUG   SenderThread:1139414 [sender.py:send():122] send: stats
2021-04-20 09:24:17,476 DEBUG   SenderThread:1139414 [sender.py:send():122] send: stats
2021-04-20 09:24:21,889 DEBUG   SenderThread:1139414 [sender.py:send():122] send: stats
2021-04-20 09:24:26,302 DEBUG   SenderThread:1139414 [sender.py:send():122] send: stats
2021-04-20 09:24:30,716 DEBUG   SenderThread:1139414 [sender.py:send():122] send: stats
2021-04-20 09:24:33,565 WARNING MainThread:1139414 [internal.py:wandb_internal():146] Internal process interrupt: 2
2021-04-20 09:24:33,565 ERROR   MainThread:1139414 [internal.py:wandb_internal():149] Internal process interrupted.
2021-04-20 09:24:33,717 INFO    SenderThread:1139414 [sender.py:finish():814] shutting down sender
2021-04-20 09:24:33,717 INFO    WriterThread:1139414 [datastore.py:close():258] close: /home/ubuntu/evgeny/GEP-forecasts/EVERGI/wandb/run-20210420_092403-3bw8bbsh/run-3bw8bbsh.wandb
2021-04-20 09:24:33,719 INFO    HandlerThread:1139414 [handler.py:finish():532] shutting down handler
2021-04-20 09:24:35,173 INFO    MainThread:1139414 [internal.py:handle_exit():78] Internal process exited
