2021-04-09 11:01:57,796 INFO    MainThread:921080 [wandb_setup.py:_flush():69] setting env: {}
2021-04-09 11:01:57,796 INFO    MainThread:921080 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-09 11:01:57,796 INFO    MainThread:921080 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '4e022d9a965c0e513287d998fbd6fd1d46056300'}
2021-04-09 11:01:57,796 INFO    MainThread:921080 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-09 11:01:57,796 INFO    MainThread:921080 [wandb_setup.py:_flush():69] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f456829c4c0>
2021-04-09 11:01:57,796 INFO    MainThread:921080 [wandb_init.py:_log_setup():319] Logging user logs to /home/ubuntu/evgeny/GEP-forecasts/EVERGI/wandb/run-20210409_110157-120v0kv9/logs/debug.log
2021-04-09 11:01:57,797 INFO    MainThread:921080 [wandb_init.py:_log_setup():320] Logging internal logs to /home/ubuntu/evgeny/GEP-forecasts/EVERGI/wandb/run-20210409_110157-120v0kv9/logs/debug-internal.log
2021-04-09 11:01:57,797 INFO    MainThread:921080 [wandb_init.py:init():352] calling init triggers
2021-04-09 11:01:57,797 INFO    MainThread:921080 [wandb_init.py:init():357] wandb.init called with sweep_config: {}
config: {'batch_size': 1500, 'architecture': 'RNN with forward lags for temporal', 'dataset': 'Columbia', 'epochs': 100, 'patience': 10}
2021-04-09 11:01:57,797 INFO    MainThread:921080 [wandb_init.py:init():372] re-initializing run, found existing run on stack: 1xm392uh
2021-04-09 11:01:57,801 INFO    MainThread:921080 [wandb_run.py:finish():1078] finishing run ujohn33/3days_forcast/1xm392uh
2021-04-09 11:01:57,802 INFO    MainThread:921080 [wandb_init.py:_jupyter_teardown():250] cleaning up jupyter logic
2021-04-09 11:01:57,840 INFO    MainThread:921080 [jupyter.py:save_history():237] saving 16 cells to _session_history.ipynb
2021-04-09 11:01:57,847 INFO    MainThread:921080 [wandb_run.py:_config_callback():669] config_cb None None {'batch_size': 1500, 'architecture': 'RNN with forward lags for temporal', 'dataset': 'Columbia', 'epochs': 100, 'patience': 10, '_wandb': {'session_history': 'code/_session_history.ipynb'}}
2021-04-09 11:01:57,855 INFO    MainThread:921080 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 0
2021-04-09 11:01:57,856 INFO    MainThread:921080 [wandb_run.py:_restore():1364] restore
2021-04-09 11:01:58,343 INFO    MainThread:921080 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 22178
  total_bytes: 22178
}

2021-04-09 11:02:00,353 INFO    MainThread:921080 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 994936
  total_bytes: 1235457
}

2021-04-09 11:02:02,358 INFO    MainThread:921080 [wandb_run.py:_wait_for_finish():1515] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1235457
  total_bytes: 1235457
}

2021-04-09 11:02:03,816 INFO    MainThread:921080 [wandb_run.py:_show_files():1737] logging synced files
2021-04-09 11:02:03,823 INFO    MainThread:921080 [wandb_init.py:init():401] starting backend
2021-04-09 11:02:03,823 INFO    MainThread:921080 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-09 11:02:03,826 INFO    MainThread:921080 [backend.py:ensure_launched():123] starting backend process...
2021-04-09 11:02:04,033 INFO    MainThread:921080 [backend.py:ensure_launched():127] started backend process with pid: 935874
2021-04-09 11:02:04,036 INFO    MainThread:921080 [wandb_init.py:init():406] backend started and connected
2021-04-09 11:02:04,059 INFO    MainThread:921080 [wandb_init.py:init():446] updated telemetry
2021-04-09 11:02:04,061 INFO    MainThread:921080 [wandb_init.py:init():465] communicating current version
2021-04-09 11:02:04,972 INFO    MainThread:921080 [wandb_init.py:init():470] got version response upgrade_message: "wandb version 0.10.25 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-09 11:02:04,973 INFO    MainThread:921080 [wandb_init.py:init():478] communicating run to backend with 30 second timeout
2021-04-09 11:02:05,227 INFO    MainThread:921080 [wandb_init.py:init():503] starting run threads in backend
2021-04-09 11:02:06,686 INFO    MainThread:921080 [wandb_run.py:_console_start():1422] atexit reg
2021-04-09 11:02:06,687 INFO    MainThread:921080 [wandb_run.py:_redirect():1285] redirect: SettingsConsole.WRAP
2021-04-09 11:02:06,687 INFO    MainThread:921080 [wandb_run.py:_redirect():1320] Wrapping output streams.
2021-04-09 11:02:06,687 INFO    MainThread:921080 [wandb_run.py:_redirect():1336] Redirects installed.
2021-04-09 11:02:06,687 INFO    MainThread:921080 [wandb_init.py:init():527] run started, returning control to user process
2021-04-09 14:45:52,067 INFO    MainThread:921080 [wandb_init.py:_jupyter_setup():271] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f44d86d8e80>
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_setup.py:_flush():69] setting env: {}
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '4e022d9a965c0e513287d998fbd6fd1d46056300'}
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_setup.py:_flush():69] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f456829c4c0>
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_init.py:_log_setup():319] Logging user logs to /home/ubuntu/evgeny/GEP-forecasts/EVERGI/wandb/run-20210409_144552-lana8wlq/logs/debug.log
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_init.py:_log_setup():320] Logging internal logs to /home/ubuntu/evgeny/GEP-forecasts/EVERGI/wandb/run-20210409_144552-lana8wlq/logs/debug-internal.log
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_init.py:init():352] calling init triggers
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_init.py:init():357] wandb.init called with sweep_config: {}
config: {'batch_size': 1500, 'architecture': 'RNN with forward lags for temporal', 'dataset': 'Columbia', 'epochs': 100, 'patience': 10}
2021-04-09 14:45:52,071 INFO    MainThread:921080 [wandb_init.py:init():372] re-initializing run, found existing run on stack: 120v0kv9
2021-04-09 14:45:52,074 INFO    MainThread:921080 [wandb_run.py:finish():1078] finishing run ujohn33/3days_forcast/120v0kv9
